# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./src/Jazz2Tileset.h \
    ./src/Jazz2FormatDataBlock.h \
    ./src/Jazz2FormatParseException.h \
    ./src/Version.h \
    ./src/PCTilesetConverter.h
SOURCES += ./src/Jazz2Tileset.cpp \
    ./src/Jazz2FormatDataBlock.cpp \
    ./src/Jazz2FormatParseException.cpp \
    ./src/PCTilesetConverter.cpp
